name: seq_logger
description: The package that writes the logs to the database and sends these logs to the SEQ LOG Api service.
version: 1.0.8
repository: https://github.com/Performans-Dev/seq_logger/
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.1
  intl: ^0.19.0
  path: ^1.8.2
  path_provider: ^2.0.12
  sqflite: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

